name: dockerfiles
services:
  dockerfiles:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .user_guid.env
    image: dockerfiles
    stdin_open: true # Keeps stdin open for the service
    tty: true # Allocates a pseudo-TTY
    volumes:
      - ${DATA_PATH:-./data}:/app/data
      - ${CONFIG_PATH:-./config}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json
