# docker compose build dockerfiles
# docker compose run --rm dockerfiles list node lts
# docker compose run --rm dockerfiles config
# docker compose run --rm dockerfiles
name: dockerfiles
services:
  dockerfiles:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .user_guid.env
    image: ismailbouajaja/dockerfiles
    stdin_open: true # Keeps stdin open for the service
    tty: true # Allocates a pseudo-TTY
    volumes:
      - ${LOGS_PATH:-./data/logs}:/app/data/logs
      - ${CONFIG_FILEPATH:-./config/config.json}:/app/config/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json
